[package]
name = "ded"
version = "0.1.0"
edition = "2021"

[dependencies]
tui-textarea = { path = "..", features = ["search"] }
crossterm = { workspace = true }
ratatui = { workspace = true }
shellexpand = "3.1.0"
