[package]
name = "ded"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.26.1" }
shellexpand = "3.1.0"
tui-textarea = { path = "..", features = ["search"] }
